### ISSUE TITLE
Create a website

### ISSUE THREAD

**Issue by mikaelrandy** [atoum/atoum#524]
The idea of creating a website is an old hat.

Today, during the forumphp 2015, some people have spoken about the lack of communication around atoum.
Some ideas were given : publish release process, publish some user feedbacks, tips, ...

I propose myself to build a website, powered by github page, to start all of this.

If you feel its a good idea, i need right to create new repo on the organization.

**Comment by Hywan** [comment]
I am working on it with @jubianchi. This was a “secret” project I was hoping to release for the ForumPHP but I am late (being a dady… well, you know!). Here is the repository: https://github.com/Hywan/Atoum-website/.

**Comment by Hywan** [comment]
@mikaelrandy So, the website is advanced (50%). An example is online: http://atoum.mnt.io/.

**Comment by Hywan** [comment]
Oops, misclicked on the “close” button, sorry!

**Comment by mikaelrandy** [comment]
Wow ! Why dont KISS and just use a [Github page](https://pages.github.com/) system ?

For me, with this system, it's easy for everyone to propose new content, correct typos, ... ([a little exemple](https://github.com/K-Phoen/rulerz/pull/24))

**Comment by Hywan** [comment]
@mikaelrandy Actually, that pretty simple :-/. That basic HTML templates with Ember. We also use an API to communicate with Github to get more information like latest releases, links to release attachments & co. It works well and it's pretty simple. More than 50% of the work lands. We just need to write 3 other pages (I am currently working on it) and design some icons and here we go.

**Comment by mikaelrandy** [comment]
@Hywan how to you handle content (blog post) creation ?

**Comment by Hywan** [comment]
A subsite maybe, or like your proposal, 1 file per blog post.

**Comment by Hywan** [comment]
The current work is pretty much static.

**Comment by Hywan** [comment]
@mikaelrandy And to be frank, we don't need a blog yet. We first require a website and then, when we will have regular people wanting to write a blog post, then we can think about a blog. The website needs to:
1. Describe atoum,
2. Expose features,
3. Links to the documentation,
4. Links to the extensions,
5. Some community and about stuff.

That's the first basis. A rewrite can be introduce later but I don't want to have an overkill tool that will never be released.

**Comment by mikaelrandy** [comment]
I'm not convinced :/
In my mind, we need to launch a simple system to create a real communication around atoum (as the public told to us yesterday at forumPHP) more than create a complete application.

**Comment by Hywan** [comment]
@mikaelrandy Who talked about a complete application? That's a **very** simple website, almost 100% static. A blog post = an application = at least 1 blog writer. We don't have any blog writer yet, so no need to develop a blog. However, we have several resources we need to organise and expose. That's exactly what the current work does.

**Comment by Hywan** [comment]
@mikaelrandy Also, sorry but https://github.com/Hywan/Atoum-website/ contains 1 view file, 1 PHP resource file, 1 index file and some static files. I don't get the “complete application” and the “not KISS”.

**Comment by mikaelrandy** [comment]
@Hywan if i have to understand how the website works, it's an application.
Github pages work only on Github PR and markdown. How could we be more simple ?

Today, there is no one to write, but maybe because there is no place to write ;)

Again, the feedback of the community we had yesterday was not about finding release or repo, but about communication aroud the project.

In my mind (but my english is certainly too poor to clearly explain my POV), to allow contribution from all people who have 2mn, we have to use the simplest and most common tools.

**Comment by Hywan** [comment]
https://github.com/Hywan/Atoum-website/blob/master/Application/View/Index.html it's a single page application. I don't know why HTML is more difficult to understand than Markdown but I know that Markdown does not allow 99% of what HTML provides. Ember is wildly spread, so that's not difficult too. A simple `README` can explain where documents land and here we go, that's **not** more difficult than a Github page.

If you would like to have a blog based on Markdown, that's less than 50 LOC with the current work (API to get blog post written in Markdown + Ember to read blog posts from the API + Markdown to HTML to print them). In this scenario, 1 blog post = 1 file. Still easy to contribute.

What is the problem exactly? I don't get it.

**Comment by mikaelrandy** [comment]
The website as you have build it is based on a system that is not standard.
Github page is now really popular, and a lot a people know how to use it easily.

Just this morning, while reading a documentation, i have found a little type, and i was one click far away from the possibility to propose a correction, using a PR. Nothing can be as simple as this.

HTML is more powerfull than markdown, but more complicated to avoid breaking entire website.
Markdown is perfect to write blogpost because it's very simple to read and write.

And there is another problem : Github page are hosted by Github itself, not a home application

But it seem we have opposite point of view. What about ask for another opinions ?

**Comment by Hywan** [comment]
Not standard? Ember is not a well-known tool? Sorry, I should have used a really obscure and undocumented language like we did for the documentation? About the documentation, there is a separate repository though.

Yes, ask someone else opinion and discard existing effort, that's a really good idea. We have a **very** existing small website (working and tested on several devices, regarding screen sizes, GPU performances, network latences etc.) that does **what we want to**, but let's do a rewrite with something less powerful. This is a very good idea. A rewrite = restart from 0. Current work is more than 50% over.

**Comment by mikaelrandy** [comment]
@Hywan do not be angry ! Why exposing my POV is a fault ?
You told me the fact you have made half of the work is an argument to chose this work, but have you asked the rest of the community about this idea ?
You are convinced that our work is the best choice, i respect it but i have a different point of view, nothing else, nothing personal ! 

I could understand that my idea is a bad idea, but for now, i dont have any feedback about the rest of @atoum/all 

You told half of the work is done. Great, but have you ask others about this idea ?
Recently, i have spent 1 day to propose a complete PR to composer ... who was refused ([link](https://github.com/composer/composer/issues/4591)). It's the game when building something without talking about it.

And, to be really clear, dont stop your work, it's just my point of view and it's possible i'm the one to think like this

**Comment by Hywan** [comment]
@mikaelrandy Yes, I was angry. I spent nights and nights trying to polish the website (not finished yet). I was building a surprise. So, not talking about it was relatively natural. I asked feedbacks from Hoa's community and especially @jubianchi about the goals of the website. I kept atoum's community apart because… surprise ;-).

I am sad that you're proposing something else directly because it does not seem “simple” for you.

**Comment by mikaelrandy** [comment]
@Hywan again, i do not critize what you have done. I'm "just" not convinced that the good choice.
The result of your work is beautiful, its clear, but i have some fears about usability of all atoum __users__ (not only __contributors__)

I understand the fact that you want to make a surprise, but it's not a reason to force people to be ok with your choices. And it's the same for this issue : i __propose__ an idea, to collect feedback, and i'm aware that other people could disagree with me (like you are).

But, again, the fact that you have already done a lot of work is not an argument who work for me.

I think i will not push this issue forward if nobody else gives an opinion.

I certainly have the same frustration than you : as someone else have a final idea of what is the good idea, i just have to agree with.

**Comment by jubianchi** [comment]
Hi here!

First of all, no need to be angry about anything here, everyone should be involved in deciding what we should do and how.

> I spent nights and nights trying to polish the website

@Hywan you did a great job, but as I already told you, perhaps a simpler system would suffice. To quote you:

> 1. Describe atoum,
> 2. Expose features,
> 3. Links to the documentation,
> 4. Links to the extensions,
> 5. Some community and about stuff.

Here, we don't need PHP to do that, we don't even need any frontend framework, just plain old HTML page, I think.

We have to ship something easy to use, deploy and maintain. Anyone should be able to fix a typo, deploy the new site with ease. Using PHP would require configuring accesses to servers, granting them, ...

I don't think we have what we need to maintain a "complex" website, we don't either have anyone with strong admin skills to monitor/supervise it.

What I'm trying to say here is, why not just stick to the atoum mantra: we want **simple** things. We want **modern** thing. We want **extensible** things: plain HTML will proivde us at least two of those points. If we later need to extend the website to cover much more use-cases (blog, status pages, <whatever>) we can still ove forward later.

Finally, here is my POV:

* we should start small and simple: plain HTML on GH pages
* move it forward as needs arise
* do not exclude any solution in the future, be it Hoa, Symfony, Silex, Slim, Express or whatever
* be pragmatic: we don't have enough time to maintain something big, and even if we had time, I think we should spend this time on atoum itself because this is what users will use in the end. 

The website is just an entry, it has to be cool, sexy but the technical aspect of it is not important for now.

Again, please do not take any of those comment as an offense, we are just (and we should continue) discussing what we should do and how.

BTW, thanks @Hywan for your work and everyone contributing to this thread.

**Comment by mageekguy** [comment]
Huge +1.

**Comment by Hywan** [comment]
Anyone to port current website to Github pages then?

**Comment by mikaelrandy** [comment]
I will try this evening during my train travel

**Comment by Hywan** [comment]
Cool.

**Comment by jubianchi** [comment]
can we close this one as work is being done in atoum/atoum.github.io ?

**Comment by mikaelrandy** [comment]
@jubianchi ok for me. I have the same reflexion yesterday night.
