### ISSUE TITLE
Code Coverage - Function signature is reported as not covered although the whole function is

### ISSUE THREAD

**Issue by krtek4** [atoum/atoum#666]
I have a small PHP class which is fully tested but atoum only report 88% of coverage.

For two functions that uses the new variadic syntax for functions (ie the `...` operator) the function signature is reported as being non covered.

![image](https://cloud.githubusercontent.com/assets/963772/19610576/70a750b2-97dd-11e6-8afd-02644b51869f.png)

I am not sure if the issues lies on atoum side or the Xdebug extension. AFAIK atoum only works with Xdebug for coverage, but I gladly test with anything else if I am mistaken.

The project is here : https://github.com/functional-php/trampoline

**Comment by Grummfy** [comment]
Thanks. We are working on the integration with phpdbg.

I will let @agallou , @jubianchi or @Hywan respond to the rest

**Comment by krtek4** [comment]
I had a look at the output from the Xdebug extension and the error comes from error. For a unknown reason at the time, the lines with a type signature containing the `...` operator are reported as being unexecuted.

I'll open a bug on Xdebug about that.

**Comment by Hywan** [comment]
Hey hey @krtek4 😃,

Can you provide the bug to XDebug please?
Also, what version of XDebug are you using? Since recently, XDebug was applying a very dumb coverage (line/instruction code coverage, which has never been a valid criteria, see [Code coverage](https://en.wikipedia.org/wiki/Code_coverage)). Now it provides real criteria and I wonder what criteria were enabled.

Thanks!

**Comment by krtek4** [comment]
I provided the link as an update to my last comment yesterday.

It's the latest version, 2.4.1

**Comment by Hywan** [comment]
Thanks!
