### ISSUE TITLE
Memory limit seems not to be respected

### ISSUE THREAD

**Issue by trasher** [atoum/atoum#808]
I set `memory_limit` running atoum, but it does not seems to be respected:
```
php -d memory_limit=512M vendor/bin/atoum --max-children-number 1 [...]
Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes)
```

See https://circleci.com/gh/trasher/glpi/2054

**Comment by jubianchi** [comment]
@trasher this is an expected behavior due to how atoum runs itself and execute the tests.

When you run `bin/atoum` it is run through a PHP process. Then the default strategy is to use the concurrent engine which will spawn a dedicated process for each test method.

To avoid the error you are getting you have to tell atoum to set a different `memory_limit` for the chidren processes. You can do that using the `-p`/`--php` flag. Something like this should work:

```
vendor/bin/atoum --max-children-number 1 -p 'php -d memory_limit=512M` [...]
```

**Comment by trasher** [comment]
Sorry for the delay, did not have time to test... Well, you're right, using the flag is the solution, sorry for the noise :-)
