### ISSUE TITLE
How to access private and protected properties

### ISSUE THREAD

**Issue by naspy971** [atoum/atoum#851]
Hello,

I can't find in the documentation a way to call private and protected properties of a tested class.

For methods, I use invoke() over the method, but it seems to me that atoum does not provide a way to achieve it on class properties.

**Comment by Grummfy** [comment]
hello,

Indeed, atoum, doesn't give access to non public method & properties.

For non-public method, there is a plugins http://extensions.atoum.org/extensions/visibility (see https://github.com/atoum/visibility-extension#install-it for installation). But nothing for the properties.

I'm not sure to have a real use case in my mind for properties access change. Most of the time, when I find myself requiring some change on properties, I find that my architecture design was not really good and change the code instead of trying to push it in the unit testing.

If really you need some change, perhaps, you will require to play a bit with reflexion.

**Comment by naspy971** [comment]
Thanks for the reply.

It was not for change purpose, but just to get the value. If atoum does not allow such thing, I'll use a simple getter to do just that.

**Comment by naspy971** [comment]
Thanks for the reply.

It was not for change purpose, but just to get the value. If atoum does not allow such thing, I'll use a simple getter to do just that.
